#!/usr/bin/env python
import os, sys
import json
import requests

SERVER = "idefix:7900"
server = os.environ.get('SERVER', SERVER)

ACTIONS = ('add', 'get')

def usage():
    print "Usage: katzenkey [get|add] [data]"
    print "  katzenkey get user@provider"
    print "  katzenkey add user@provider key"

post = requests.post

if __name__ == '__main__':
    if len(sys.argv) not in (3, 4):
        usage()
        sys.exit(1)
    action = sys.argv[1]

    if action == 'get':
        user = sys.argv[2]
        ret = post(server + '/getkey', {'user': user}).json()
        print ret['key']

    if action == 'add':
        user = sys.argv[2]
        key = sys.argv[3]
        ret = post(server + '/add', {'user': user, 'key': key})
        if ret.status_code == 200:
            print "ok"
